# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testCamera0427_02' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    pod 'Masonry'

  # Pods for testCamera0427_02

  target 'testCamera0427_02Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testCamera0427_02UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
